import{useState}from'react';import{Link}from'react-router';
import{estimateFundCosts,FUND_COST_TERMS,type FundCostComparison}from'../../../../packages/backend/fund-cost.ts';
export function meta(){return[{title:'两只C类费用比较 · 经纬'}];}
const money=(n:number)=>n.toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
function ResultTable({result:r}:{result:FundCostComparison}){return <><table className="cost-table"><caption>按当前列示费率不变的静态演算 · 人民币元</caption><thead><tr><th>费用项目</th>{r.funds.map(f=><th key={f.code}>{f.code==='007339'?'易方达C':'华夏C'}<small>{f.code}</small></th>)}</tr></thead><tbody>{[['销售服务费','service_fee_yuan'],['赎回费','redemption_fee_yuan'],['以上两项合计','total_fee_yuan']].map(([label,key])=><tr key={key}><th>{label}</th>{r.funds.map(f=><td key={f.code}>{money(f[key as 'service_fee_yuan'])}</td>)}</tr>)}</tbody></table><p className="cost-difference">华夏减易方达：<strong>¥{money(r.difference.total_fee_yuan)}</strong><span>仅上述两项假设费差，不能据此认定哪只应该买或换。</span></p><p className="reader-note">分项先四舍五入至分，再合计和相减，差值可按表内数字复核。</p></>;}
export default function Compare(){const[amount,setAmount]=useState(''),[days,setDays]=useState(''),[result,setResult]=useState<FundCostComparison|null>(null),[error,setError]=useState('');function calculate(event:React.FormEvent){event.preventDefault();try{const r=estimateFundCosts({amount:Number(amount),holding_days:Number(days)});setResult(r);setError('');}catch{setResult(null);setError('请输入大于0的有限金额，以及大于0的整数持有天数。');}}
return <main id="main" className="reader-page comparison-page"><p className="eyebrow">同一指数 · 两只C类</p><h1>费用差，放到你的金额和期限里看</h1><p className="reader-intro">两只都跟踪沪深300，同时持有不增加方向分散。这里只估算销售服务费和赎回费，不代表全部实际成本。</p><form onSubmit={calculate} noValidate className="cost-form"><label>静态估算金额（元）<input type="number" inputMode="decimal" name="amount" min="0.01" step="0.01" value={amount} onChange={e=>{setAmount(e.target.value);setResult(null);}} placeholder="如 10000"/></label><label>已确认持有自然日数<input type="number" inputMode="numeric" name="holding_days" min="1" step="1" value={days} onChange={e=>{setDays(e.target.value);setResult(null);}} placeholder="如 7"/></label><button type="submit">估算这两项费用</button></form>{error&&<p className="cost-error" role="alert">{error}</p>}<p className="reader-note">假设持仓价值和赎回金额始终等于输入金额，按365日年计提。申购、赎回的确认起止计数未核实，请不要直接用申请日间隔判断7日档位。输入不会保存或发给模型。</p>
{result&&<section className="cost-result" aria-live="polite"><h2>{result.long_holding?'这个期限的未来实际总额仍未知':'本次静态估算'}</h2><p>{money(result.amount)}元 · {result.holding_days}个已确认自然日。{result.long_holding?'未来费率与超过一年的停止计提安排未核实，不能将旧年费率线性外推为长期省费承诺。':'结果仅按原概要所列合同费率计算，实际适用费用尚未核实。'}</p>{result.long_holding?<details className="long-cost-scenario"><summary>查看“费率全程不变”的假设演算</summary><ResultTable result={result}/></details>:<ResultTable result={result}/>}<p className="cost-critical">2026费改具体执行日、直销与代销、优惠及存量持有期安排尚未核实。实际成本和实际差额不能由本表确定。</p><details className="research-sources"><summary>计算假设与未计入项目</summary>{result.assumptions.map(t=><p key={t}>{t}</p>)}{result.limitations.map(t=><p key={t}>{t}</p>)}</details></section>}
<section className="reader-setting"><h2>列示条款与原文日期</h2>{FUND_COST_TERMS.map(f=><div className="cost-terms" key={f.code}><h3>{f.name}<small>{f.code}</small></h3><p>销售服务合同年费率 {(f.annual_service_rate*100).toFixed(2)}%；确认持有不足7日，赎回费1.50%；达到7日，原概要列示为0。</p><details className="research-sources"><summary>原文与每日计提口径</summary><p>按前一日C类基金资产净值 × 年费率 ÷ 当年天数，每日计提，按月支付。当年不固定为365天，跨闰年需按实际日期分段。</p>{f.sources.map(s=><p key={s.url+s.pdf_page}><a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a><small>送出 {s.published_at} · PDF 第{s.pdf_page}页</small></p>)}</details></div>)}<p className="reader-note">服务费已从基金资产计提，不能从已扣费净值收益里再扣一遍。管理费、托管费及其他费用未纳入；是否配置、是否换基金还要看方向判断和原条件。</p></section><div className="reader-actions"><Link to="/">回到本期研究 →</Link><Link to="/situation">修改我的情况 →</Link></div></main>;}
