import type {FundChange} from '../backend/fund-updates.ts';
import type {ResearchDecision} from './research.ts';
export type SourceRef = { article_id: string; revision: number; source: string; url: string; published_at: string; checked_at?:string; data_as_of?:string; fragments: string[]; display_fragments?:string[] };
export type ParagraphBasis = {kind:'fact'|'inference'|'action';refs:{article_id:string;fragment_index:number}[]};
export type Section = { heading: string; paragraphs: string[]; refs?: string[]; basis?:ParagraphBasis[]; chart?: 'rates' | 'gdp' | 'transmission' | 'lpr-comparison' };
export type MarketEvidence = {as_of:string;close:number;pe_ttm:number;pb:number;dividend_yield:number;previous_year_end:{pe_ttm:number;pb:number};daily:{date:string;close:number}[];source:SourceRef};
export type FeeContext = {share_class:'C';investor_scope:string;channel_scope:string;effective_from:string|null;holding_terms:string;announcement:SourceRef|null;checked_at:string;verification:'implementation_verified'|'implementation_unverified';unverified:string[]};
export type OperationView = { next_watch?:string;method_version?:string;fee_regulation?:SourceRef; market?:MarketEvidence; research_conditions?:{key:string;label:string;baseline:string;watch:string;trigger:string;automatic:boolean}[]; reviewed_on:string; performance_period:string; held:{action:'加'|'持'|'减'|'观察'|'无法评估'; text:string}; unheld:{action:'加'|'持'|'减'|'观察'|'无法评估'; text:string}; reason:string; counterargument:string; change_conditions:string[]; funds:{a_class?:{code:string;service:string;subscription:string;redemption:string;document_date:string;source_ref_id:string};fee_context?:FeeContext;fee_holding_terms?:string;fee_channel_scope?:string;fee_effective_from?:string;fee_announcement?:string;field_checked_at?:Record<string,string>;code:string;name:string;role:string;management:string;custody:string;service:string;total:string;subscription:string;redemption:string;trade_status:string;period_return:string;benchmark_return:string;difference:string;tracking_error:string;benchmark:string;document_date:string}[]; comparison_note:string; gaps:string[] };
export type Article = { slug: string; title: string; deck: string; category: string; read_minutes: number; kind: 'analysis' | 'background'; sections: Section[]; operation_view?:OperationView };
export type Interpretation = { topic_key: string; claim_key: string; claim: string; evidence_ids: string[]; mechanism: string[]; conditions: string[]; alternatives: { explanation: string; evidence_ids: string[] }[]; related_story_ids: string[]; previous_claim_version_ids: string[] };
export type FinanceVersion = {
 research?:ResearchDecision;
 editorial_review?:{note:string;reviewed_at:string}; editorial_edited_at?:string; review?:{required:boolean;status:'pending'|'approved';reason:string;checked_at:string;changes:FundChange[];condition_changes?:string[];reviewed_at?:string}; id: string; story_id: string; previous_version_id: string | null; version: number; as_of: string; generated_at: string; input_hash: string; input_refs: SourceRef[]; article: Article; interpretation: Interpretation; changes: { kind: 'initial'|'maintain'|'supplement'|'revise'; summary: string; evidence_ids: string[] }; origin: 'editor' | 'model'; published_at: string | null };
export type Material = { id: string; source_id: string; url: string; title: string; published_at: string; revision: number; content_hash: string; paragraphs: string[]; collected_at: string; topic_keys: string[] };
export type CandidateEvent = { id:string; event_key:string; story_id:string; subject:string; action:string; occurred_period:string|null; title:string; topic_key:string|null; material_ids:string[]; evidence_ready_ids:string[]; status:'identified'|'needs_event'|'needs_evidence'; reason:string|null; updated_at:string };
export type GenerationTask = { id:string; event_id:string; evidence_hash:string; status:'pending'|'running'|'draft'|'done'|'failed'; waiting_reason:string|null; material_ids:string[]; version_id:string|null; created_at:string; updated_at:string };
export type CollectionRun = { id:string; started_at:string; finished_at:string; sources:{source:string;discovered:number;stored:number;revised:number;errors:string[]}[] };
export type BudgetLedger = { id:string; limit_micro_cny:number; reserved_micro_cny:number; approved_at:string; reservations:{id:string;task_id:string|null;amount_micro_cny:number;at:string;outcome:'started'|'completed'|'uncertain'}[] };
