import {writeFile} from 'node:fs/promises';
const targets=await(await fetch('http://127.0.0.1:9231/json')).json();
const target=targets.find((t:{type:string})=>t.type==='page');if(!target)throw new Error('isolated_chrome_page_missing');
const ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise<void>(resolve=>ws.addEventListener('open',()=>resolve(),{once:true}));
let seq=0;const pending=new Map<number,{resolve:(v:any)=>void;reject:(e:Error)=>void}>();ws.addEventListener('message',e=>{const d=JSON.parse(String(e.data)),p=pending.get(d.id);if(p){pending.delete(d.id);d.error?p.reject(new Error(d.error.message)):p.resolve(d.result);}});
const command=(method:string,params:object={})=>new Promise<any>((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
async function evaluate(expression:string){const r=await command('Runtime.evaluate',{expression,returnByValue:true});if(r.exceptionDetails)throw new Error('page_expression_failed');return r.result.value;}
async function navigate(path:string){await command('Page.navigate',{url:'http://127.0.0.1:4410'+path});for(let i=0;i<30;i++){if(await evaluate('document.readyState')==='complete')break;await new Promise(r=>setTimeout(r,100));}await evaluate('document.fonts.ready.then(()=>true)');await new Promise(r=>setTimeout(r,250));}
async function shot(name:string){const r=await command('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await writeFile(new URL('../evidence/'+name,import.meta.url),Buffer.from(r.data,'base64'));}
await command('Page.enable');const checks:any[]=[];
await command('Emulation.setDeviceMetricsOverride',{width:1440,height:1150,deviceScaleFactor:1,mobile:false});await navigate('/');
checks.push(JSON.parse(await evaluate('JSON.stringify({page:"home_desktop",width:innerWidth,scroll:document.documentElement.scrollWidth,title:document.querySelector("h1")?.textContent,figure:document.querySelectorAll(".market-figure").length,keyFields:document.querySelectorAll("input[name=key]").length})')));await shot('第四版_首页_桌面.png');
await command('Emulation.setDeviceMetricsOverride',{width:390,height:1450,deviceScaleFactor:1,mobile:true});await navigate('/');
checks.push(JSON.parse(await evaluate('JSON.stringify({page:"home_phone",width:innerWidth,scroll:document.documentElement.scrollWidth,title:document.querySelector("h1")?.textContent,overflow:document.documentElement.scrollWidth>innerWidth})')));await shot('第四版_首页_手机.png');
await navigate('/articles/csi300-hold-and-fund-choice');
checks.push(JSON.parse(await evaluate('JSON.stringify({page:"article_phone",width:innerWidth,scroll:document.documentElement.scrollWidth,title:document.querySelector("h1")?.textContent,rows:document.querySelectorAll(".operation-comparison tbody tr").length,feeContexts:document.body.innerText.includes("具体费用生效日"),implementationUnknown:document.body.innerText.includes("未核实"),overflow:document.documentElement.scrollWidth>innerWidth})')));await shot('第四版_文章_手机.png');
const law=await evaluate('(()=>{const s=[...document.querySelectorAll("details.source")].find(d=>d.textContent.includes("证监会"));if(!s)return false;s.open=true;s.scrollIntoView({block:"start",behavior:"instant"});return true})()');if(!law)throw new Error('fee_rule_source_missing');await new Promise(r=>setTimeout(r,150));
checks.push(JSON.parse(await evaluate('JSON.stringify({page:"fee_rule_expanded",open:[...document.querySelectorAll("details.source")].find(d=>d.textContent.includes("证监会"))?.open,sourceLinks:[...document.querySelectorAll("details.source[open] a")].map(a=>a.href),width:innerWidth,scroll:document.documentElement.scrollWidth})')));await shot('第四版_费改依据_手机.png');
await navigate('/articles/csi300-hold-and-fund-choice?version=3');checks.push(JSON.parse(await evaluate('JSON.stringify({page:"old_v3",headline:document.querySelector("h1")?.textContent,correction:document.body.innerText.includes("此前费用比较未核清2026年费改适用条件")})')));
await navigate('/topics/china-equity-index');checks.push(JSON.parse(await evaluate('JSON.stringify({page:"topic",headline:document.querySelector("h1")?.textContent,currentClaimNarrowed:document.body.innerText.includes("未证实同样本盈利改善")})')));
const report={checked_at:new Date().toISOString(),browser:'isolated headless Google Chrome; temporary profile',checks};await writeFile(new URL('../evidence/第四版_真实Chrome核查.json',import.meta.url),JSON.stringify(report,null,2));console.log(JSON.stringify(report));await command('Browser.close');ws.close();
