// Rebuilds packages/backend/index-pe-seeds.ts: official CSI daily PE for the added CSI indices and
// 蛋卷基金's weekly PE for the others. The first three indices keep their own seed (fetch-pe-history.ts).
// Run: node scripts/fetch-index-pe-seeds.ts
import {writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fetchDanjuanHistory, fetchPeHistory, parsePeHistory, mergePeHistory, historyUrl, PE_HISTORY_URL, type ValuationPoint} from '../packages/backend/valuation-history.ts';
import {INDEX_CODES, RETURN_INDEX_CODES, sourceOf, type IndexCode} from '../packages/backend/valuation-indexes.ts';

async function csi(index: IndexCode): Promise<ValuationPoint[]> {
  // Long ranges come back in one response; two windows keep each response moderate.
  const query = new URLSearchParams({indexCode: index, startDate: '20050101', endDate: '20151231'});
  const response = await fetch(`${PE_HISTORY_URL}?${query}`, {headers: {'User-Agent': 'JingweiResearch/0.1'}, signal: AbortSignal.timeout(60_000)});
  if (!response.ok) throw new Error(`pe_history_http_${response.status}`);
  const body = JSON.parse(await response.text());
  const early = Array.isArray(body.data) && body.data.length ? parsePeHistory(body, '2015-12-31', index) : [];
  const late = await fetchPeHistory('2016-01-01', {index});
  // Like the CSI 300 seed, start where daily data is continuous.
  return mergePeHistory(early, late).filter(p => p.date >= '2011-01-01');
}

// Rows before these dates are not part of the continuous series: 中证1000 reads 7–10 times until a
// one-day move to 49 on 2014-09-25 (a different scale), and 科创50 has a lone 2016-01-01 row before its
// 2020 data. Real one-day jumps elsewhere stay; only these leading segments are dropped.
const STARTS: Partial<Record<IndexCode, string>> = {'000852': '2014-09-25', '000688': '2020-07-06'};

const seeds: Record<string, unknown> = {};
for (const index of INDEX_CODES.filter(code => !(RETURN_INDEX_CODES as readonly string[]).includes(code))) {
  const points = (sourceOf(index) === 'csi' ? await csi(index) : await fetchDanjuanHistory(index, {span: 'all'})).filter(p => p.date >= (STARTS[index] ?? ''));
  seeds[index] = {source_url: historyUrl(index), fetched_at: new Date().toISOString(), first: points[0].date, last: points.at(-1)!.date, rows: points.length,
    data: points.map(p => `${p.date.replaceAll('-', '')}:${p.pe_ttm}`).join(',')};
  console.log(`${index} ${points.length} rows ${points[0].date} – ${points.at(-1)!.date}`);
}
const file = path.resolve(import.meta.dirname, '../packages/backend/index-pe-seeds.ts');
await writeFile(file, `// Generated by scripts/fetch-index-pe-seeds.ts. Do not edit by hand.\nexport const EXTRA_PE_SEEDS: Record<string, {source_url: string; fetched_at: string; first: string; last: string; rows: number; data: string}> = ${JSON.stringify(seeds, null, 1)};\n`);
