// Rebuild the offline public code/name/type seed. No reader data is accessed.
import {readFile, writeFile} from 'node:fs/promises';
import {FUND_LIST_URL, parseFundList} from '../packages/backend/fund-list.ts';

const response = process.argv[2] ? null : await fetch(FUND_LIST_URL, {signal: AbortSignal.timeout(90_000)});
if (response && !response.ok) throw new Error(`fund_list_http_${response.status}`);
const funds = parseFundList(response ? await response.text() : await readFile(process.argv[2], 'utf8'));
const snapshot = {source_url: FUND_LIST_URL, fetched_at: new Date().toISOString(), funds};
await writeFile(new URL('../packages/backend/fund-list-seed.ts', import.meta.url),
  `// Public 天天基金 code/name/type list, fetched ${snapshot.fetched_at}.\n// Source: ${FUND_LIST_URL}\n// Generated by scripts/fetch-fund-list.ts; not holding data.\nimport type {FundList} from './fund-list.ts';\nexport const FUND_LIST_SEED: FundList = JSON.parse(${JSON.stringify(JSON.stringify(snapshot))});\n`);
console.log(`Public fund list: ${funds.length} entries, fetched ${snapshot.fetched_at}`);
