// Rebuilds packages/backend/csi300-pe-seed.ts from the official CSI endpoint.
// Run: node scripts/fetch-pe-history.ts
import {writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fetchPeHistory, parsePeHistory, mergePeHistory, PE_HISTORY_URL} from '../packages/backend/valuation-history.ts';

// The endpoint returns long ranges in one response; two windows keep each response moderate.
const early = await (async () => {
  const query = new URLSearchParams({indexCode: '000300', startDate: '20050101', endDate: '20151231'});
  const response = await fetch(`${PE_HISTORY_URL}?${query}`, {headers: {'User-Agent': 'JingweiResearch/0.1'}, signal: AbortSignal.timeout(30_000)});
  if (!response.ok) throw new Error(`pe_history_http_${response.status}`);
  return parsePeHistory(JSON.parse(await response.text()), '2015-12-31');
})();
const late = await fetchPeHistory('2016-01-01');
// A single 2005-01-01 row precedes a multi-year gap; the series starts where daily data is continuous.
const points = mergePeHistory(early, late).filter(p => p.date >= '2011-01-01');
const body = points.map(p => `${p.date.replaceAll('-', '')}:${p.pe_ttm}`).join(',');
const file = path.resolve(import.meta.dirname, '../packages/backend/csi300-pe-seed.ts');
await writeFile(file, `// Generated by scripts/fetch-pe-history.ts from ${PE_HISTORY_URL} (CSI 300, rolling PE TTM).\n// ${points.length} rows, ${points[0].date} to ${points.at(-1)!.date}. Do not edit by hand.\nexport const CSI300_PE_SEED_SOURCE = ${JSON.stringify({url: PE_HISTORY_URL, fetched_at: new Date().toISOString(), first: points[0].date, last: points.at(-1)!.date, rows: points.length})} as const;\nexport const CSI300_PE_SEED = '${body}';\n`);
console.log(`${points.length} rows ${points[0].date} – ${points.at(-1)!.date}`);
