// Run: node scripts/fetch-total-return-history.ts. Leaves the PE seeds untouched.
import {writeFile} from 'node:fs/promises';
import {seedHistory} from '../packages/backend/valuation-history.ts';
import {fetchTotalReturnHistory, OUTCOME_INDICES, TOTAL_RETURN_URL, type OutcomeIndex} from '../packages/backend/total-return-source.ts';

const start = seedHistory().points[0].date;
const end = '2026-09-30';
await Promise.all((Object.keys(OUTCOME_INDICES) as OutcomeIndex[]).map(async index => {
  const points = await fetchTotalReturnHistory(index, start, end);
  if (!points.length || points[0].date !== start || points.at(-1)!.date !== end) throw new Error(`total_return_seed_incomplete_${index}`);
  const file = `../packages/backend/${index}-total-return-seed.ts`;
  const source = {url: TOTAL_RETURN_URL, index_code: OUTCOME_INDICES[index].code, name: OUTCOME_INDICES[index].name_cn, fetched_at: new Date().toISOString(), first: points[0].date, last: points.at(-1)!.date, rows: points.length};
  const body = points.map(p => `${p.date.replaceAll('-', '')}:${p.close}`).join(',');
  await writeFile(new URL(file, import.meta.url), `// Official CSI total return closes (includes dividends). Generated by scripts/fetch-total-return-history.ts.\nexport const TOTAL_RETURN_SOURCE = ${JSON.stringify(source)} as const;\nexport const TOTAL_RETURN_SEED = '${body}';\n`);
  console.log(`${index} / ${source.index_code}: ${points.length} rows, ${source.first} – ${source.last}`);
}));
